drop table if exists stg_fs_info;

create table stg_fs_info
(
  `id` bigint NOT NULL,
  `title` text,
  `description` text,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `finance_code` text,
  `contact_person_name` text,
  `contact_person_email` text,
  `donor` bigint DEFAULT NULL,
  `direct_donor` bigint DEFAULT NULL,  
  `status` int DEFAULT NULL,
  `type` bigint DEFAULT NULL,
  `division_id` bigint DEFAULT NULL,
  `global` tinyint ,
  `w1w2` tinyint ,
  `lead_center_id` bigint DEFAULT NULL,
  `id_phase` bigint NOT NULL,
  `funding_source_id` bigint NOT NULL,
  `extended_date` date DEFAULT NULL,
  `fs_idname` text,
  `grant_amount` double,
  `is_active` tinyint NOT NULL,
  `current_end_date` date,
  `year` int,
  `global_unit_id` bigint,
  `budget_amount` double,
  `budget_amount_allocated` double,
  `pending_budget_amount` double,
  `has_budget_allocated` tinyint ,
  `has_budget` tinyint,
  `fs_link` text,
  `CRP` varchar(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
