Drop table if exists `stg_deliverables_info`;

CREATE TABLE `stg_deliverables_info` (
  `id_phase` bigint DEFAULT NULL,
  `global_unit_id` bigint DEFAULT NULL,
  `deliverable_id` bigint DEFAULT NULL,
  `project_id` bigint DEFAULT NULL,
  `subcategory_type_id` bigint DEFAULT NULL,
  `subcategory_type_name` varchar(255) ,
  `category_type_id` bigint DEFAULT NULL, 
  `category_type_name` varchar(255),
  `dissemination_channel` VARCHAR(50),
  `adopted_license` VARCHAR(13),
  `title` text,
  `description` text,
  `dissemination_URL` text,
  `deliverable_group` text,
  `journal` text,
  `volume` text,
  `issue` text,
  `pages` text,
  `is_ISI_journal` bigint,
  `is_open_access` bigint,
  `metadata_title` text,
  `DOI` text,
  `Handle` text,
  `Citation` text,
  `key_output_name` text,
  `coa_key_output_name` text,
  `coa_id` varchar(20),
  `coa_description` text,
  `marlo_link` varchar(300),
  `CRP` varchar(20),
  status bigint,
  delivery_year bigint
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
